# CircleCI configuration file
# Mojaloop build Orb
version: 2.1

# setup: true
orbs:
  build: mojaloop/build@1.0.64
workflows:
  checks:
    jobs:
      - build/pr_title_check:
          name: PR title
          filters:
            branches:
              ignore:
                - main
                - master
  build_and_test:
    jobs:
      - build/setup:
          name: Setup
          filters: &setup-filter
            branches:
              ignore:
                - /feature/*
                - /bugfix/*
            tags:  &setup-tags
              only: /v\d+(\.\d+){2}(-[a-zA-Z-][0-9a-zA-Z-]*\.\d+)?/
          context: org-global

      - build/test_dependencies:
          name: Dependencies
          filters:
            branches:
              ignore:
                - main
                - master
          requires:
            - Setup
      - build/test_deprecations:
          name: Deprecations
          filters: *setup-filter
          requires:
            - Setup
      - build/test_lint: &test-condition
          name: Lint
          filters: *setup-filter
          requires:
            - Setup
      - build/test_unit:
          name: Unit
      
