# CircleCI configuration file
# Mojaloop build Orb
version: 2.1

setup: true
orbs:
  build: mojaloop/build@1.0.64
workflows:
  setup:
    jobs:
      - build/setup:
          name: Setup
          context: org-global

          