# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  connector_greeting:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Malawi Connector Greeting"
  # Job two with a unique name
  connector_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Malawi Connector Goodbye"

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - connector_greeting
      - connector_goodbye