# CircleCI configuration file
# Mojaloop build Orb
version: 2.1

setup: true
orbs:
  build: mojaloop/build@1.0.64
workflows:
  checks:
    jobs:
      - build/pr_title_check:
          name: PR title
          filters:
            branches:
              ignore:
                - main
                - master
  build_and_test:
    jobs:
      - build/setup:
          name: Setup
          context: org-global
      - build/test_dependencies:
          name: Dependencies
          requires:
            - Setup
      - build/test_deprecations:
          name: Deprecations
          requires:
            - Setup
