# CircleCI configuration file
# Mojaloop build Orb
version: 2.1

setup: true
orbs:
  build: mojaloop/build@1.0.64
workflows:
  setup:
    jobs:
      - build/test_lint:
          name: Run ESLint
          yarn_lock: "true"

          